// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDIP9yELaAzEmdKZDUWKk1-ABeHQDqC8s',
    appId: '1:496398017354:web:374705fbfb4f14ea31d7b3',
    messagingSenderId: '496398017354',
    projectId: 'flutterlab-firebase-557fa',
    authDomain: 'flutterlab-firebase-557fa.firebaseapp.com',
    storageBucket: 'flutterlab-firebase-557fa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL1X3jCmpqk2salNypSnHO5q99L51Mg0Y',
    appId: '1:496398017354:android:58db2f4bc1a726bc31d7b3',
    messagingSenderId: '496398017354',
    projectId: 'flutterlab-firebase-557fa',
    storageBucket: 'flutterlab-firebase-557fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXMOs3TqrGXXDy3STA3SdxSgHIqy5rvMg',
    appId: '1:496398017354:ios:f4275ef86c7e831831d7b3',
    messagingSenderId: '496398017354',
    projectId: 'flutterlab-firebase-557fa',
    storageBucket: 'flutterlab-firebase-557fa.appspot.com',
    iosClientId:
        '496398017354-s03sqot4ikde4g43t7j8nblqan3nhogr.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLabFirebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXMOs3TqrGXXDy3STA3SdxSgHIqy5rvMg',
    appId: '1:496398017354:ios:f4275ef86c7e831831d7b3',
    messagingSenderId: '496398017354',
    projectId: 'flutterlab-firebase-557fa',
    storageBucket: 'flutterlab-firebase-557fa.appspot.com',
    iosClientId:
        '496398017354-s03sqot4ikde4g43t7j8nblqan3nhogr.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLabFirebaseAuth',
  );
}
